### ISSUE TITLE
Negative number of years

### ISSUE THREAD

**Issue by SeLLeRoNe** [mf-social/ps-date-countdown#8] opened 2020-02-11 17:39 UTC
Hi there,

since last update for some reason the "years" attribute became a negative value.
![image](https://user-images.githubusercontent.com/9599441/74262672-9e084380-4cfd-11ea-94da-e2522ef4b8c7.png)

I have checked now the configuration and documentation to see if there was something new I wasn't aware of but it doesn't look like.

The config it's fairly simple, the only difference is that I am using the secret file to store the dates:
```
  - service: python_script.date_countdown
    data:
      name: Andrea
      type: birthday
      date: !secret andrea_birthday
```

Any clue?

Thanks :)
Andrea

**Comment by point-4ward** [comment] 2020-02-12 00:15
I'm offline atm because we're having a major refurb downstairs, but I'll have a look as soon as I can :slightly_smiling_face:

**Comment by SeLLeRoNe** [comment] 2020-02-12 10:15
Sure no worries :)

**Comment by cyrosy** [comment] 2020-02-18 15:03
I can confirm this issue, it seems to have been introdued by #7 
@mf-social I can submit a PR if you on't have time to look into this, i got it fixed locally

**Comment by point-4ward** [comment] 2020-02-18 15:08
By all means chuck a PR in and I'll merge it later with your other one and bundle it all in to one release - appreciate the assist 🙂

**Comment by point-4ward** [comment] 2020-02-18 15:12
(or just push another commit to the other PR that I haven't merged yet if that's easier)

**Closed as completed** 2020-02-19 21:39 UTC

**Comment by point-4ward** [comment] 2020-02-19 21:54
... And released.

Thanks @cyrosy  :slightly_smiling_face: 

@SeLLeRoNe , let me know if any further issues :+1:

**Comment by SeLLeRoNe** [comment] 2020-02-19 22:59
Thank you very much! 
It's working perfectly now ;)

**Comment by SeLLeRoNe** [comment] 2020-02-20 00:31
Not sure it's on the Data Countdown side, but last update is not "downloadable" from HACS, it's just spin as if it is updating and then it stops without having the updated version downloaded.

I noticed when I tried before but I didn't care too much and I manually downloadded it.
Now I was performing the same update on my father's HA instance and I see the same issue (different house/connection/PC)

**Comment by point-4ward** [comment] 2020-02-20 10:29
@SeLLeRoNe - are you able to tell me if this is still the case please? I think it takes a few hours for HACS to update but it definitely should be there by now.

I'm still offline (last day today, thankfully!) so I can't see until I start getting all my stuff back in tomorrow :slightly_smiling_face:

**Comment by cyrosy** [comment] 2020-02-20 10:39
I cannot apply the update from HACS either.
Seems like an HACS issue, I cannot install any of the python scripts.
@SeLLeRoNe can you install / update any other python script from HACS ?
If not, we should open an issue in their repository

Edit : I just saw you already did open an issue in HACS, posting for reference :
https://github.com/hacs/frontend/issues/79

**Comment by SeLLeRoNe** [comment] 2020-02-20 10:47
No, I can't install any Python Script :)

**Comment by point-4ward** [comment] 2020-02-20 11:26
Hopefully a HACS issue then, I'll try and keep an eye out 😁
